name: $(Date:yyyyMMdd)$(Rev:.r)
trigger:
  branches:
    include:
    - master
  paths:
    exclude:
    - README.md
pr:
  branches:
    include:
    - master
  paths:
    exclude:
    - README.md
resources:
  repositories:
  - repository: azuredevopstemplates
    type: github
    name: phcaguiar/azuredevopstemplates
    ref: refs/tags/v1.0.1
    endpoint: phcaguiar

stages:
  - stage: Build
    displayName: Build
    jobs:
      - template: build.yml@azuredevopstemplates
        parameters:
          vmImage: 'ubuntu-18.04'
  - stage: Deploy
    displayName: Deploy
    jobs:
      - template: deploy.yml@azuredevopstemplates
        parameters:
          vmImage: 'ubuntu-18.04'